<script
  setup
  lang="ts"
></script>

<template>
  <footer>
    <div
      class=""
    >
      <div>
        <div>
          Vue
          Plant
          Store
        </div>
        <p>
          Lorem.
        </p>
        <p>
          Lorem
          ipsum
          dolor
          sit
          amet,
          consectetur
          adipisicing
          elit.
          At
          consectetur
          neque
          quidem
          vel
          vitae
          voluptates.
        </p>
      </div>
      <div>
        <h5>
          Menu
          title
        </h5>
        <ul>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
        </ul>
      </div>
      <div>
        <h5>
          Menu
          title
        </h5>
        <ul>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
          <li>
            <a
              href="#"
              >lorem</a
            >
          </li>
        </ul>
      </div>
      <div>
        <h5>
          Mailing
        </h5>
        <form
          action=""
        >
          <input
            type="email"
            name="mail"
            id=""
          />
          <button
            type="submit"
          >
            Submit</button
          >/
        </form>
      </div>
    </div>
  </footer>
</template>

<style
  scoped
></style>
